branches:
  except:
    - circleci
    - travisci
    - gh-pages
    - build_linux_64
    - build_osx_64

install:
  - ps: choco install -y -r swig --version 3.0.9
  - ps: choco install -y -r lua
  - ps: refreshenv

before_build:
  - cmake -G "Visual Studio 14 2015 Win64" -DTINYSPLINE_ENABLE_CSHARP=TRUE -DTINYSPLINE_ENABLE_D=TRUE -DTINYSPLINE_ENABLE_JAVA=TRUE.

build:
  project: tinyspline.sln
